apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-wpp
spec:
  selector:
    matchLabels:
      app: bot-wpp
  template:
    metadata:
      labels:
        app: bot-wpp
    spec:
      containers:
        - name: bot-wpp
          image: bot-wpp
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - name: api-port
              containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bot-wpp-secret-dev
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-wpp-secret-dev
                  key: db-password
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: bot-wpp-secret-dev
                  key: jwt-secret
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bot-wpp-config-dev
                  key: DATABASE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bot-wpp-config-dev
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bot-wpp-config-dev
                  key: DB_PORT
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: bot-wpp-config-dev
                  key: APP_NAME
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: bot-wpp-config-dev
                  key: API_PORT
            - name: DATABASE_URL
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DATABASE)
