apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bot-wpp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot-wpp
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
