apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: bot-wpp
  newName: qzzdocker24/bot-wpp
  newTag: 025c40e83ccf0b5945b363a6d32df6f53b5f236d
