apiVersion: v1
kind: Service
metadata:
  name: bot-wpp
  namespace: bot-wpp
spec:
  selector:
    app: bot-wpp
  ports:
    - name: bot-service-port
      port: 80
      targetPort: api-port
  type: LoadBalancer
