apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bot-wpp-monit
  labels:
    release: prometheus
spec:
  endpoints:
    - port: bot-service-port
      interval: 30s
      path: /metrics
  jobLabel: monitoring
  selector:
    matchLabels:
      app: bot-wpp
